import { Router } from "express";
import { listProduct, getProductById, createProduct, updateProduct, deleteProduct } from "../controllers/product.controller.js";
import { authenticate } from "../middlewares/auth.middleware.js";
import { authorizeRoles } from "../middlewares/role.middleware.js";
const router = Router();
router.use(authenticate);
router.get("/", listProduct);
router.get("/:id", getProductById);
router.post("/", authorizeRoles("admin"), createProduct);
router.put("/:id", authorizeRoles("admin"), updateProduct);
router.delete("/:id", authorizeRoles("admin"), deleteProduct);
export default router;